######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 16:02:58 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
